name: Deploy
on:
  pull_request:
    branches: [ "master" ]
    types: [ closed ]
  workflow_run:
    workflows:
      - "Build and Deploy"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      
      - name: Take Version
        run: |
          # Get the current version from the pom.xml file
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Version: $current_version"
          echo "$current_version" > current_version.txt

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key current_version.txt ${USER_NAME}@${HOSTNAME}:~/current_version.txt
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '"
            # Now we have got access to EC2, and we will start the deploy.
            cat curent_version.txt
            CURRENT_VERSION=$(cat current_version.txt)
            sudo docker run --name my-app ${{ secrets.DOCKERHUB_USERNAME }}/my-app:$CURRENT_VERSION "'
